### ISSUE TITLE
Do you have any official document cases?

### ISSUE THREAD

**Issue by youthinn** [unicape/use-wagmi#1]
Do you have any official document cases?

**Comment by unicape** [comment]
> Do you have any official document cases?

@youthinn sorry not yet, You can view `examples/vue` in the `main` branch

**Comment by youthinn** [comment]
> > Do you have any official document cases?
> 
> @youthinn sorry not yet, You can view `examples/vue` in the `main` branch

![image](https://github.com/unicape/use-wagmi/assets/96770326/fe3d532c-fcab-4d2b-8e33-222331651bab)
Try the example to report an error, using npm, do I need to configure something else?
