### ISSUE TITLE
Using examples to prompt for exceptions

### ISSUE THREAD

**Issue by youthinn** [unicape/use-wagmi#11]
@unicape Hello, I am using the latest version of the example to connect to the wallet, but I will still be prompted export named 'InjectedConnector'，I want to export Meat Mask and Coinbase from it, which will also throw the same exception
![image](https://github.com/unicape/use-wagmi/assets/96770326/2c39e463-64d3-48bb-a824-12f0da293f56)

**Comment by youthinn** [comment]
This is my code:
![image](https://github.com/unicape/use-wagmi/assets/96770326/32952c2d-9d0c-4a7c-9fd4-1ae01882672b)
![image](https://github.com/unicape/use-wagmi/assets/96770326/0e949828-3915-4e7a-8c59-94fddab9b58a)
The package version I am using:
![image](https://github.com/unicape/use-wagmi/assets/96770326/4e5b31e1-55c4-4f41-8b21-a9374eac0974)

**Comment by unicape** [comment]
@youthinn import { InjectedConnector } from 'use-wagmi/connectors/injected'
