### ISSUE TITLE
use-wagmi with Web3Modal Vue SDK

### ISSUE THREAD

**Issue by denniarems** [unicape/use-wagmi#113]
is there any way to use the latest web3model vue package with use-wagmi ?
link: https://docs.walletconnect.com/web3modal/vue/about

i'm trying to create like this 
![image](https://github.com/unicape/use-wagmi/assets/39432770/fd7cd540-25b8-461d-8eaa-ddd1650901df)

**Comment by glitch-txs** [comment]
you don't need to use `createConfig` if you're using `defaultWagmiConfig`

**Comment by glitch-txs** [comment]
I created a working example, you'll need a WalletConnect project ID
https://github.com/glitch-txs/vue-wagmi-web3modal

**Comment by denniarems** [comment]
thanks,and let me check this by composable functions

**Comment by denniarems** [comment]
It will be very nice if we create a discussion threads on github or discord.

**Comment by glitch-txs** [comment]
which discord? I guess we could add it to the examples folder here too? @unicape

**Comment by denniarems** [comment]
I'm getting a different unusual error 

![image](https://github.com/unicape/use-wagmi/assets/39432770/be67c65f-ec36-409b-b253-8b9b9ecc4195)
![image](https://github.com/unicape/use-wagmi/assets/39432770/2b17bc56-620f-4f61-9628-2e11b77be1c1)


getting  Error: `useConfig` must be used within `UseWagmiPlugin`.

but if call useTransaction or useWaitForTransaction outside the function it works. but i don't know how to wait for the transaction. 
suggest me a good approach, please.

**Comment by denniarems** [comment]
I figured things out this way. please suggest to me if there are any better ways to do that
![image](https://github.com/unicape/use-wagmi/assets/39432770/c849d48b-4631-4541-81d7-73dbe82eedbc)

**Comment by unicape** [comment]
> discord

There is currently no discord channel

**Comment by unicape** [comment]
@denniarems  Here is an open source project using use-wagmi. I hope it can help you. [ModuFlow useContractWrite hook](https://github.com/TsengMJ/ModuFlow/blob/main/web/composables/utils/useContractWrite.ts)

**Comment by dennisDappgenie** [comment]
> I created a working example, you'll need a WalletConnect project ID https://github.com/glitch-txs/vue-wagmi-web3modal

can you update the repo based on new release

**Comment by glitch-txs** [comment]
> can you update the repo based on new release

We're releasing support for Wagmi v2 this week.

@unicape would you be ok if I open a PR to add this example in your repository?
I'd also like to discuss with our team the possibility of adding your repo in our documentation. Please let me know your thoughts on this, thanks!

**Comment by unicape** [comment]
@glitch-txs  Yes Very welcome

**Comment by reslear** [comment]
> I created a working example, you'll need a WalletConnect project ID https://github.com/glitch-txs/vue-wagmi-web3modal
 
@glitch-txs  sorry did you move the repository or delete it ?

**Comment by glitch-txs** [comment]
yes because it was using an old version, I'm waiting for @unicape to merge his work into Wagmi's main repo, we can improve Web3Modal support officially from WalletConnect once that's done :)

**Comment by reslear** [comment]
@glitch-txs ok, and now there's no temporary solution?

**Comment by glitch-txs** [comment]
Yes, you can still implement We3Modal, I haven't had the time to look into it, we can set up an example together if you want. Wanna make a boilerplate repo?

**Comment by reslear** [comment]
@glitch-txs yes, if you don't mind and have the time :)

**Comment by reslear** [comment]
<img width="421" alt="Screenshot 2024-04-05 at 08 44 15" src="https://github.com/unicape/use-wagmi/assets/12596485/d9753833-41c6-4890-829a-247ebda8b78b">

But there is a small problem with types however I customized it turned out to be easy - and it works )
