### ISSUE TITLE
Unable to integrate web3auth using use-wagmi library

### ISSUE THREAD

**Issue by denniarems** [unicape/use-wagmi#12]
Hi there,

I'm currently experiencing issues while attempting to integrate the web3auth authentication system using the use-wagmi library. Here are the details of the issue.
![image](https://github.com/unicape/use-wagmi/assets/39432770/33394a68-c2d9-4b68-8b3b-06d6fe6cd133)
![image](https://github.com/unicape/use-wagmi/assets/39432770/9a157a6e-f3f0-476a-92e9-fd947239c3a0)

**Comment by reslear** [comment]
`web3auth` use `wagmi` 0x version without `viem` support

**Comment by unicape** [comment]
@reslear It doesn't look like it supports Vue

**Comment by unicape** [comment]
@reslear Also, not all applications of the wagmi ecosystem can be used if you use use-wagmi
