### ISSUE TITLE
Module level directives cause errors when bundled, "use client" in "useToken.js" was ignored.

### ISSUE THREAD

**Issue by Fyfe0203** [unicape/use-wagmi#154]
![image](https://github.com/unicape/use-wagmi/assets/84113519/b4063ac4-a340-496a-8eca-e20e3f9a0d58)

The above situation will occur in the build, but it does not affect normal use.

**Comment by unicape** [comment]
This is a bug caused by a rollup, you can either turn it off in options or ignore it

**Comment by reslear** [comment]
@Fyfe0203 https://github.com/TanStack/query/issues/5175#issuecomment-1482196558
