### ISSUE TITLE
bug: Error when using use-wagmi with pinia nuxt3

### ISSUE THREAD

**Issue by ffierce** [unicape/use-wagmi#164]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

latest

### Current Behavior

When using **use-wagmi** with **pinia** in **nuxt3** I get this error.
![Screen](https://github.com/unicape/use-wagmi/assets/153300677/35114220-4f3d-4581-a99d-d1e5f4a0e22e)

dependencies:
- nuxt: 3.9.0
- viem: latest
- use-wagmi: latest
- pinia: 2.1.7

**Comment by ffierce** [comment]
I found a solution but it's not pretty at all, every time I have to pass the config argument.

`const account = useAccount({ config })
`

**Comment by ffierce** [comment]
When I call a transaction I still get the error: Error: vue-query hooks can only be used inside setup() function or functions that support injection context.

**Comment by vitusha-rat** [comment]
@ffierce 
> I found a solution but it's not pretty at all, every time I have to pass the config argument.
> 
> `const account = useAccount({ config }) `

If you are using nuxt - do a plugin initialization to make the wagmi config global as shown here (in general you can just copy from here:https://github.com/unicape/use-wagmi/blob/main/playgrounds/nuxt/plugins/wagmi.ts )

If you are using vue - here is an example:https://github.com/unicape/use-wagmi/blob/main/playgrounds/vite-vue/src/main.ts

@unicape It would be much appreciated if you could add this to the main part of the documentation <3

**Comment by ffierce** [comment]
Hello! I did this at the first stage. Pinia doesn't see this.

**Comment by reslear** [comment]
@PfanP https://github.com/unicape/use-wagmi/blob/main/packages/vue/package.json#L91

**Comment by PfanP** [comment]
When I'm trying to install the use-wagmi to nuxt project, it produces version versatility issue
![Screen Shot 2024-02-19 at 11 41 09 AM](https://github.com/unicape/use-wagmi/assets/36354694/ba8c2660-582f-4ff1-87e6-f5371901b62d)

**Comment by reslear** [comment]
@PfanP `npm install --legacy-peer-deps --force`
