### ISSUE TITLE
bug: How to use accountWatch useAccountEffect ?

### ISSUE THREAD

**Issue by dataexcess** [unicape/use-wagmi#168]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.3.5

### Current Behavior

Hello, I want a vue callback when the account is being switched in the wallet. Is that possible using use-wagmi? It is not clear to me how. and I couldnt find an example.

Thanks

**Comment by unicape** [comment]
Provide examples

**Comment by unicape** [comment]
No reply for a long time. Temporarily closed.
