### ISSUE TITLE
bug: doesn't connect with WalletConnect (first connection ANDROID)

### ISSUE THREAD

**Issue by Pasha8914** [unicape/use-wagmi#172]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

^1.3.4

### Current Behavior

Packages:
-   vue 3.4.15
-   viem 2.7.6
-   vite 5.0.12
-   @wagmi/connectors 4.1.13
-   @wagmi/core 2.6.4

Devices:
- Chrome Version 122.0.6261.129 (Official Build) (arm64)
- Mobile Metamask **Android**  v7.16.0 (1265)

When connecting via **WalletConnect** for the first time, it does not connect the wallet the first time. (reconnection will work correctly)

_works correctly for IOS_

### Expected Behavior

The wallet should connect the first time

### Steps To Reproduce

- open browsers with a clean site data
- click on WalletConnect
- open Metamask on your phone (must be closed) 
- click Scan 
- scan QR

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://codesandbox.io/p/devbox/wagmi-vue-4g8lmj

https://github.com/Pasha8914/use-wagmi-approve

### Anything else?

In order to run **codesandbox**, you need to open new terminal tab and run the command 
`yarn;yarn dev`

**Comment by unicape** [comment]
Sorry, I don’t have an Android device. You can try using @wagmi/core if you have this problem.
