### ISSUE TITLE
how to use reactive args?

### ISSUE THREAD

**Issue by reslear** [unicape/use-wagmi#25]
hi @unicape thx for good lib :) 

also I have a problem with arg in `prepareWriteContract`, I need get arg from backend before initialize, and the set to reactive or ref, and then call refetch, but wagmi use old data.

repro: https://stackblitz.com/edit/vitejs-vite-qvjgfi?file=examples%2Fvite%2Fsrc%2Fcomponents%2FWriteContractPrepared.vue

```ts
const args = reactive({
  tokenId: BigInt(1),
})

const { config, refetch } = usePrepareContractWrite({
  ...wagmiContractConfig,
  functionName: 'mint',
  args: [args.tokenId],
  enabled: false,
})

const { write, data, error, isLoading, isError, isSuccess } =
  useContractWrite(config)

async function prepare() {
  // emulate xhr getting args
  await new Promise((r) => setTimeout(r, 2000))
  args.tokenId = BigInt(2)

  console.log(config)

  refetch()
}
```

<img width="1050" alt="Screenshot 2023-07-03 at 19 08 20" src="https://github.com/unicape/use-wagmi/assets/12596485/43b02202-c5a5-4064-acbb-1bcab2a23404">

I use `computed` and `ref` but no result, how is the right solution for this? 

we used @wagmi/core temporarily, what parameters must be passed to the `prepareWriteContract` function (account , walletClient ? ) to make it work seamlessly with `useContractWrite` from `use-wagmi` ?  

```ts
 const config = await prepareWriteContract({
   // ... abi config 
   chainId: 1
   // walletClient ? 
   // account ?
 })
``

**Comment by unicape** [comment]
@reslear reactive will lose responsiveness after deconstruction
```
const args = {
  tokenId: ref(BigInt(1))
}
```

**Comment by reslear** [comment]
@unicape yes i use `ref`, but result is same... i update repl
<img width="1628" alt="Screenshot 2023-07-03 at 19 45 07" src="https://github.com/unicape/use-wagmi/assets/12596485/c0555796-90a8-4479-97bb-749f465b9974">

**Comment by unicape** [comment]
@reslear Your `enabled` is `false`

**Comment by reslear** [comment]
Thanks, works well ;)
