### ISSUE TITLE
bug: Type issue when using useContractRead composable.

### ISSUE THREAD

**Issue by vitusha-rat** [unicape/use-wagmi#58]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.3.9

### Current Behavior

 const { data: symbol } = useContractRead({
         ^ biging | number | boolean | string | void
    ...tokenConfig,
    functionName: "symbol",
  });

### Expected Behavior

 const { data: symbol } = useContractRead({
         ^ string | undefined
    ...tokenConfig,
    functionName: "symbol",
  });

**Comment by unicape** [comment]
@vitusha-rat Link to Minimal Reproducible Example

**Comment by unicape** [comment]
Temporarily closed due to no reply for a long time
