### ISSUE TITLE
wait for using Viem :) 

### ISSUE THREAD

**Issue by reslear** [unicape/use-wagmi#6]
hi @unicape wait for Viem support :)
https://github.com/unicape/use-wagmi/tree/develop
🔥

**Comment by unicape** [comment]
@reslear yes, stay tuned

**Comment by reslear** [comment]
Hi @unicape, can you already publish with the tag next alpha for testing:)

**Comment by unicape** [comment]
@reslear Sorry, not yet, expect a release this week

**Comment by unicape** [comment]
@reslear A new version has been released. Please use the latest version. There are some changes in the API. Please check the README or example. This issue will be closed first.
