### ISSUE TITLE
useWaitForTransaction pass the hash parameter

### ISSUE THREAD

**Issue by lw-94** [unicape/use-wagmi#67]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

use-wagmi    v0.4.0

### Current Behavior

Using it this way causes data.value.hash to lose responsive. This disables the isLoading of useWaitForTransaction. As long as .value is used to pass parameters, the return value of the hook will be invalidated. Is there any solution?

### Steps To Reproduce

```typescript
const {
  write,
  isLoading: loading1,
  isSuccess,
  data
} = useContractWrite(config)
const { isLoading: loading2 } = useWaitForTransaction({ hash: data.value?.hash })
```

**Comment by lw-94** [comment]
Currently, I use computed to keep it responsive, but I think passing .value directly should also keep it responsive. See if you can make changes.

**Comment by unicape** [comment]
@lw-94  Sorry we rely on `vue` response

**Comment by lw-94** [comment]
@unicape Okay, can you give an example of how useWaitForTransaction's isLoading can respond to changes normally? If you use data.value.hash to pass parameters, isLoading will always be false.

**Comment by unicape** [comment]
@lw-94 `.value` will lose the response, so `isLoading` is always false
You should do this `{ hash: computed(() => data.value?.hash) }`

**Comment by lw-94** [comment]
@unicape hh, this is what I did before, thanks～～

**Comment by ernaneluis** [comment]
> @lw-94 Sorry we rely on `vue` response

this is indeed very important info!
