### ISSUE TITLE
Metamask on safari

### ISSUE THREAD

**Issue by lostarchitect** [unicape/use-wagmi#73]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.4.3

### Current Behavior

Upon trying to connect to metamask on safari on my phone, i get the `Connector not found` error.

### Expected Behavior

I would like for this to trigger a deep link into metamask.

### Steps To Reproduce

1. Use `use-wagmi` on safari on a mobile device
2. Try to connect to metamask

**Comment by unicape** [comment]
@lostarchitect
Because there is no wallet plugin in Safari
You can use metamask app to access dapp or use wallet connect to connect
> wagmi may add the function of automatically launching the mobile wallet in a later version

**Comment by lostarchitect** [comment]
Understood! But I know for instance using WC it deeplinks into metamask, but WC2 has proven to be quite janky in that respect... I believe also the newest MM SDK release deeplinks into the metamask app for a non-mm mobile browser.

But overall sounds like this would be upstream, in `wagmi` itself?
