### ISSUE TITLE
`autoConnect` flag doesn't work as expected

### ISSUE THREAD

**Issue by yulafezmesi** [unicape/use-wagmi#74]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.4.3

### Current Behavior

Hey there, the `autoconnect` does not work as expected. when you connect any provider you want and refresh the page, the connection was gone.

### Expected Behavior

the connection should be persist as long as `autoConnect` flag is true. 

### Steps To Reproduce

1. Select any provider you want and connect
2. Refresh the page you'll see connection was gone.

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://stackblitz.com/edit/nuxt-starter-zgbggc?file=components%2FWeb3Button.vue,plugins%2Fwagmi.ts,package.json,nuxt.config.ts,app.vue

### Anything else?

i've initilized config via Nuxt plugins and also created minimal replication to see what's going on actually.

thank you!

**Comment by unicape** [comment]
@yulafezmesi 
```js
const config = createConfig({
    autoConnect: true,
    publicClient,
    connectors: [] // You need to provide the connector
  });
```

**Comment by yulafezmesi** [comment]
> @yulafezmesi
> 
> ```js
> const config = createConfig({
>     autoConnect: true,
>     publicClient,
>     connectors: [] // You need to provide the connector
>   });
> ```

@unicape Thank you for the response. however the solution didn't work. i've checked the other wagmi playgrounds, the `connectors` property didn't required for `autoConnect`

i've updated the playground, could you check over here?

https://stackblitz.com/edit/nuxt-starter-zgbggc?file=components%2FWeb3Button.vue,plugins%2Fwagmi.ts,package.json,nuxt.config.ts,app.vue

**Comment by unicape** [comment]
@yulafezmesi 
```js
const { connectors } = useConnect()
```

use this

**Comment by yulafezmesi** [comment]
Thanks, works like a charm!

**Comment by Fyfe0203** [comment]
> @yulafezmesi
> 
> ```js
> const { connectors } = useConnect()
> ```
> 
> use this

Where is this used to make autoConnect work?
