### ISSUE TITLE
useConfig does not work with @tanstack/vue-query

### ISSUE THREAD

**Issue by Melty-melts** [unicape/use-wagmi#75]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.1.8

### Current Behavior

Cannot get a working app with `useConfig` and Nuxt3. Can anyone provide a working example of `use-wagmi.ts` plugin for Nuxt3 exporting the config with useWagmiPlugin?

### Expected Behavior

Expecting no errors passing `nuxtApp.vueApp.use(UseWagmiPlugin, config)`

### Steps To Reproduce

install nuxt3
install wagmi viem use-wagmi
create use-wagmi plugin
try and use anything wagmi

stackblitz doesn't even recognize use-wagmi but I provided a minimal example there.

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://stackblitz.com/edit/github-cgbkrw-m2kxhc?file=README.md

**Comment by unicape** [comment]
@Melty-melts What exactly is the error?

**Comment by unicape** [comment]
@Melty-melts It may be that you did not download the complete dependency package
