### ISSUE TITLE
bug: <title> useSendTransaction not working properly

### ISSUE THREAD

**Issue by padi-dev-ducpc** [unicape/use-wagmi#76]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.4.3

### Current Behavior

I tried to use the useSendTransaction hook, I parsed the configuration params which are stored on pinia state. I used the function sendTransactionAsync from the hook, yesterday it was working fine but today when I called it, it returned the error (err.walk is not a function): 
![image](https://github.com/unicape/use-wagmi/assets/129250952/7af42a15-18db-4423-b4ee-9bf51bb8713a)

the configuration params look like this:
account
: 
"0xcFD64601902A56d9030835731193fD643c74F37d"
data
: 
"0x6b4e5dbf000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000008fc0000000000000000000000000000000000000000000000000000000000000001000000000000000000000000524253e41be63f275e57208603764602ef130c2d0000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000002386f26fc10000"
maxFeePerGas
: 
1.00000004
maxPriorityFeePerGas
: 
1
to
: 
"0xcd89d7ae644e15378558F2e18Db2e0492D41e637"
value
: 
"10000000000000000"

### Expected Behavior

It should work fine, parse the sendTransaction request to MetaMask wallet

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://stackblitz.com/edit/nuxt-starter-hnpxvv?file=app.vue

**Comment by unicape** [comment]
@padi-dev-ducpc 
```js
const { data: dataSend, sendTransactionAsync } = useSendTransaction(
  networkStore.transactionObject
);
const { data: dataReceipt } = useWaitForTransaction({
  // hash: dataSend.value?.hash,
  hash: computed(() => dataSend.value?.hash)
});
```

I'm not sure if `networkStore.transactionObject` is reactive but the part of `useWaitForTransaction` you should do like above

**Comment by padi-dev-ducpc** [comment]
yes the networkStore.transactionObject is reactive, it worked yesterday anyway. The problem is the sendTransactionAsync function couldn't be called

**Comment by unicape** [comment]
@padi-dev-ducpc Can you complete the code?

**Comment by padi-dev-ducpc** [comment]
u mean the full source code?

**Comment by unicape** [comment]
> u mean the full source code?

yes

**Comment by padi-dev-ducpc** [comment]
it's confidential, I'll try to figure it out. Thank you so much!

**Comment by unicape** [comment]
@padi-dev-ducpc Ok I suspect that the properties inside `networkStore.transactionObject` are not reactive and `useSendTransaction` internally deconstructs it
