### ISSUE TITLE
sendTransactionAsync does not return a Promise

### ISSUE THREAD

**Issue by padi-dev-ducpc** [unicape/use-wagmi#77]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.4.3

### Current Behavior

I want to use sendTransaction as an asynchronous function, so I call sendTransactionAsync. But it's shown that its type is a normal function. Please helpp!!!
![image](https://github.com/unicape/use-wagmi/assets/129250952/a3c9f8b5-bfdd-4d3c-9765-88539f899841)

**Comment by unicape** [comment]
@padi-dev-ducpc Fixed in 0.4.4
