### ISSUE TITLE
bug: <title>Sepolia RPC CORS Policy

### ISSUE THREAD

**Issue by padi-dev-ducpc** [unicape/use-wagmi#80]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.4.4

### Current Behavior

There's a CORS problem with Sepolia network after I connect
![image](https://github.com/unicape/use-wagmi/assets/129250952/06bf0dc3-007e-4a4b-a80a-9ff5f5e8e364)
Therefore, when I build the code and run it on a domain, this error occurs and the wagmi hooks are unable to fetch.
I config the chains by importing them from 'use-wagmi/chains'. I use 5 chains: sepolia, mainnet, polygon, bsc, arbitrum and only sepolia has this error, the rest work fine.

**Comment by unicape** [comment]
@padi-dev-ducpc You can manually modify the RPC or go to the viem repository to file issues.
