### ISSUE TITLE
bug: TypeError: Cannot write to private field

### ISSUE THREAD

**Issue by samuveth** [unicape/use-wagmi#82]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.4.4

### Current Behavior

There are two bugs here actually:

1. `onConnect` with `useAccount` isn't triggering at all. I get it to trigger sometimes when editing and saving a file but otherwise it doesn't work. Neither when clicking connect or when reloading the page and letting it reconnect.

2. When I get it to run I'm not able to do `getProvider` on the connector. I get the error `TypeError: Cannot write to private field`

### Expected Behavior

`onConnect` should trigger when connecting and when reconnecting. And I should be able to access `getProvider` without an error.

### Steps To Reproduce

Run the code locally or on stackblitz see `onConnect` isn't triggering and when it does it will throw an error when I try to access `connector.getProvider`

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://github.com/samuveth/vitejs-vite-4acvat

**Comment by unicape** [comment]
@samuveth
1. fixed in 0.4.5
2. Please use `useProvider` `connector.getProvider()` is a private property

**Comment by samuveth** [comment]
@unicape amazing thanks for the swift fix!

**Comment by samuveth** [comment]
@unicape I do not see `useProvider` anywhere in `use-wagmi` or `wagmi`.

What I'm trying to do is create a Web3Provider once the wallet is connected. Not really sure how I should approach without `getProvider`

```js 
import { Web3Provider } from '@ethersproject/providers';

  async function initProviders(connector: Config['connector']) {
    const provider = await connector?.getProvider();
    if (provider) {
      providerRef.value = provider;
      web3ProviderRef.value = new Web3Provider(provider);
    } else {
      providerRef.value = null;
      web3ProviderRef.value = null;
    }
  }
  
  ```

**Comment by unicape** [comment]
@samuveth Sorry, it's `useWalletClient`
