### ISSUE TITLE
InjectedConnector() is not found on nuxt 3

### ISSUE THREAD

**Issue by denniarems** [unicape/use-wagmi#88]
```
<script setup>
// import { InjectedConnector } from 'use-wagmi/connectors/injected'

const { address, isConnected } = useAccount()
const { connect } = useConnect({
  connector: new InjectedConnector(),
})
const { disconnect } = useDisconnect()
</script>
<template>
  <div v-if="isConnected">
    Connected to {{ address }}
    <button @click="disconnect">Disconnect</button>
  </div>
  <button v-else @click="connect">
    Connect Wallet
  </button>
</template>
```

the import is not working , the auto import also not working on nuxt 3

**Comment by unicape** [comment]
The list of automatic imports is here [functions](https://github.com/unicape/use-wagmi/blob/main/packages/nuxt/src/functions.ts)

**Comment by denniarems** [comment]
my question is how to import InjectedConnector. when i do it manually it shows modules not found error

**Comment by unicape** [comment]
<img width="520" alt="image" src="https://github.com/unicape/use-wagmi/assets/31918458/f19e58f1-6546-40c7-9cde-c28f7c9bc628">

**Comment by denniarems** [comment]
check this code: https://stackblitz.com/edit/github-brdlor?file=app.vue

also '@vueuse/nuxt' and '@use-wagmi/nuxt' have some conflicts

**Comment by reslear** [comment]
@denniarems need install `use-wagmi`, see example https://github.com/unicape/use-wagmi/tree/main/examples/nuxt

**Comment by unicape** [comment]
@denniarems Yes there are some functions with the same name and you can cancel some of the automatic imports
```js
modules: [
    '@vueuse/nuxt',
    ['@use-wagmi/nuxt', {
      excludeImports: [
        'useQuery',
        'useQueryClient',
        'useQueryClient',
        'useInfiniteQuery',
        'useContractRead',
        'useContractReads',
        'useContractWrite',
      ],
    }],
  ],
```
