### ISSUE TITLE
Do you want to synchronize a sample document?

### ISSUE THREAD

**Issue by youthinn** [unicape/use-wagmi#9]
Do you want to synchronize a sample document?According to Github's example, the wallet was not connected within 60 seconds

**Comment by youthinn** [comment]
Error reporting，The initial prompt is that there is no export createWagmi，Now it's InjecteConnector
![image](https://github.com/unicape/use-wagmi/assets/96770326/f0740e23-eb5f-4e57-b681-e9cd658cf2c1)

**Comment by youthinn** [comment]
@unicape This is my sample code. Is there anything missing?
![image](https://github.com/unicape/use-wagmi/assets/96770326/3a4a4668-be27-4ef4-bb78-2aec91cdcc17)
![image](https://github.com/unicape/use-wagmi/assets/96770326/33cd3400-e133-46a8-b7ef-d91e5c6d35ee)
![image](https://github.com/unicape/use-wagmi/assets/96770326/d8b51a61-8331-41ab-9c9c-b3866297c397)

**Comment by reslear** [comment]
bad import :) 

https://github.com/unicape/use-wagmi/blob/714058138d77c3329bcd0733fad585a94d476182/packages/vue/package.json#L49-L51

**Comment by unicape** [comment]
@reslear @youthinn A new version has been released. Please use the latest version. There are some changes in the API. Please check the README or example. This issue will be closed first.
