### ISSUE TITLE
Auto Import Support 

### ISSUE THREAD

**Issue by denniarems** [unicape/use-wagmi#93]
it will be good if we add Auto Import support to the vite projects using https://github.com/unplugin/unplugin-auto-import

sample template  : https://github.com/antfu/vitesse

**Comment by unicape** [comment]
I don’t understand. I don’t need to do anything about this, right?

**Comment by denniarems** [comment]
Sorry for the trouble; actually, I got the solution. we can use this way :
`
AutoImport({
  packagePresets: ['use-wagmi']
})
`
